# Generated by Django 2.0.1 on 2018-02-03 20:09

from django.db import migrations, models
import django.db.models.deletion
import server.generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=server.generator.long_token, max_length=255)),
                ('expires', models.DateTimeField()),
                ('scope', models.CharField(choices=[('EMAIL', 'e-mail'), ('FIRSTNAME', 'first name'), ('LASNAME', 'last name')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(help_text="Your main application's URL.")),
                ('redirect_uri', models.URLField(help_text="Your application's callback URL")),
                ('client_id', models.CharField(default=server.generator.short_token, max_length=255)),
                ('client_secret', models.CharField(default=server.generator.long_token, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=server.generator.long_token, max_length=255)),
                ('expires', models.DateTimeField(default=server.generator.get_code_expiry)),
                ('redirect_uri', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(choices=[('EMAIL', 'e-mail'), ('FIRSTNAME', 'first name'), ('LASNAME', 'last name')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Client')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=server.generator.long_token, max_length=255)),
                ('expired', models.BooleanField(default=False)),
                ('access_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to='server.AccessToken')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Client')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.UserData'),
        ),
        migrations.AddField(
            model_name='grant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.UserData'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Client'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.UserData'),
        ),
    ]
