# Generated by Django 2.0.1 on 2018-02-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_secret',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
